### ISSUE TITLE
[Documentation] Navigating the KB

### ISSUE THREAD

**Issue by skedulo-sschutz** [Skedulo/docs-issue-tracker#2]
I am finding it difficult to navigate. When I search it takes me to only one page instead of giving me a list of options like the old one did. I haven’t been taken to the right page yet. Are there any plans to work on navigation and maybe show a list of possible results? Is there a trick to searching that I’m missing?

Reducing the options for clients to search will increase the number of tech support tickets and CSM inquiries. Reducing the ability of tech support to search will increase support bugging CSMs, devs, eng...

**Comment by cgutierrez-skedulo** [comment]
I'd like to 👍 this comment!  I wrote a note to my team earlier today asking for guidance on how to best search the replacement for KnowledgeBase.  

> It used to be that when I typed in a term in the search box, KnowledgeBase would return a unique page (with a URL and everything) that listed a variety of articles and include a bit of a preview in each article as well as breadcrumbs, so I could easily identify which articles were Salesforce vs. Pulse Platform.  Now, when I search, there’s a pop-up modal that suggests articles which I have to click on individually to see more content, and it’s not clear until I start reading the article whether it relates to Platform or not.  Holler if you’ve got thoughts on how to better navigate to get the best answer.

**Comment by nwatnick** [comment]
Hi friends, is there a way to have a "Search Results" page between using the Search bar and serving the first response?

**Comment by gsheldon** [comment]
@nwatnick @skedulo-sschutz @cgutierrez-skedulo we are putting together some training materials on this that might help you with some of the issues you've mentioned. 

The search on this site is fundamentally different from Zendesk, and the more keywords you input the better the results that show in the drop-down results will be. Hitting `Enter` will just take you to the first result, which may or may not be what you are looking for depending on the search terms. 

On our old Zendesk site, there was no way to browse the documentation, so searching for a term and then scrolling through pages of vaguely related results was the best way to do that. This new site now has a very useful navigation menu on the left side that allows you to browse through each section of content without navigating away from an open page. @lizskelly is pulling together a Loom for you based on a recent demo for PD and I'm confident this will help better understand the differences and how you can use this new site structure and search to your advantage. Stay tuned!

**Comment by nwatnick** [comment]
Thanks for the info, @gsheldon . As feedback, it would still be helpful to have a "Search Results" page between the Search Bar and serving the first response. I recognize that you see this as a training issue. I see this more as a usability issue for our customers. 
We want our customers to use the KB and docs site more. More usage = more ticket deflection. And having this Search Results page would be helpful for them - especially when they need to go back and look at the next search result, etc. and are already "trained" by Google Search user flow.

**Comment by lizskelly** [comment]
@nwatnick, do you think the biggest problem is not being able to easily tell the difference between Pulse Platform and SF-specific pages from the search results? Or is that one facet of a bigger frustration with not being able to see more of a page preview before navigating there? I'm wondering if there is another angle we could help with that is more easily in our control, like starting all SF-specific page titles a certain way, for example.

**Comment by skedulo-sschutz** [comment]
Hi @lizskelly and @gsheldon ,

Here is my latest try to find anything about SMS messages on the new KB. Specifically, I want to see if SMS messages can be sent to patients for a platform client but I don't even see regular info on SMS messages, like for resources.

![image](https://user-images.githubusercontent.com/102764358/232888586-0cd0d271-a55e-453e-a065-ae3dd88543bb.png)

"sys" isn't the same as SMS. SMS didn't come up once but it is a big part of our product. 

To answer your questions, yes to all. Please understand that it is challenging to brainstorm when we don't have visibility into what can and can't be done. Thank you for listening to our concerns. We are totally willing to help if we can.

- It's not just the difference between Pulse Platform and Salesforce but being able to see that would be helpful. I don't see the word Pulse at all in the screenshot. 
- More of a page preview in the excerpt would be helpful but I'm not sure how much more helpful since I can't see what might have been shown. 
- Being able to also search blog articles would also be helpful. Recently someone was unable to find an answer in the KB but Scott Gassmann found it in the dev blog, which is hosted on a different website (Medium). 

To an earlier comment, more keywords do not improve the answers in the dropdown. Maybe we're missing searchable tags?

Might it be possible to get one of our web programmers to help out? Searching text on a website and having a results page are solved problems. If they know the way the site is set up then they can probably find the answer on stackoverflow.com or something.

If you want further examples of how and why this is failing please let me know. I can offer them up as I come across them. I don't use the KB often anymore.

Thanks again for listening! Please let us know if we can help further

**Comment by gsheldon** [comment]
Thanks for the example @skedulo-sschutz, that's really interesting. I've been investigating it today and it seems very unique to that query. Oddly, adding a trailing space after the query yields results, however, if I do the same with "Salesforce SMS" I get results without requiring a trailing space. I'm not sure why this is but I'll continue to investigate as it's a problem I'd like to solve. 

Re: "sys" - Algolia Docsearch includes typo tolerance and therefore will display close matches in results where there are fewer than 5 results that match the search terms. Again, this only seemed to happen when I searched "platform sms" specifically, not when just searching "SMS", "Salesforce SMS", "Send SMS" etc. 

Federated Search was a goal I had from the outset with consolidating documentation, however, this can be very expensive and we weren't given budget approval at that time. I'm also working on tagging our content but unfortunately, I'm having a hard time getting them to influence search results and this may be related to the limitations we have on our current tier. 

Our site's search is built using the same technology as what are widely regarded as some of the best documentation sites around - Stripe, Twilio, Gatsby, et al. The solution we currently have was built by our highly-experienced subcontractors from Stacktrace who are no longer working with us. We really have pushed this functionality to its limits on our current tier. It's not a matter of implementation so much as it is of limitation.  

I'm aware that this new site structure and search functionality is fundamentally different from what everyone is used to, but there are no red flags in our analytics to imply that users are using the documentation less than they were previously, in fact, the opposite seems to be the case. If we get to a point where this genuinely becomes a customer issue then I'm happy to revisit it but in the meantime, I think we're at an impasse and need to agree to disagree as we simply don't have the resources to re-work our search solution at this stage. 

There are some very exciting AI tools that may resolve this for us all in the near future and I'm continuing to investigate better solutions as they become available and within budget for us to implement.
